### ISSUE TITLE
App doesn't open. Blank screen

### ISSUE THREAD

**Issue by durgaswaroop** [Steccas/ProtonClient#10]
I have installed the app just yesterday. It worked fine then. But today I can't seem to open it. It is just stuck with a blank, white screen. 

![image](https://user-images.githubusercontent.com/8543652/144185453-c6b59973-6514-449e-b030-35b73bde89a4.png)

Any ideas on what can be done?

**Comment by durgaswaroop** [comment]
OK. So, it finally came up after several forced restarts. But something to look into.

**Comment by Steccas** [comment]
Ho @durgaswaroop, it does sometime happens when protonmail web servers doesn't answer.

But anyways is possibly a problem that should be solved soon because I'm going to publish a much needed update by this weekend.

Thanks for using protonmail anyways :)

**Comment by Nive9** [comment]
@durgaswaroop I've had that happen a few times. Have you tried just hitting the refresh website shortcut? (Ctrl + R on Windows/ Linux; probably Cmd + R on Mac)

That's fixed it for me every time so far.

**Comment by Steccas** [comment]
In any case, new version has been released. @durgaswaroop, if everything is ok you can close the issue.
