### ISSUE TITLE
Nativefier old build detected

### ISSUE THREAD

**Issue by strongboy54** [Steccas/ProtonClient#4]
Hello,
getting this error when opening the application, this started as of yesterday. 
![image](https://user-images.githubusercontent.com/31914358/118816582-fe037780-b8ba-11eb-9027-b5e365156aa2.png)

Everything still works, but I can only assume it should be updated.

**Comment by cesarcamps** [comment]
It is happened to me too :(

**Comment by Steccas** [comment]
Yeah, the repo is updated but I didn't have the time to release the builds

**Comment by Steccas** [comment]
Hi everyone, I published all the builds. WIndows installer is coming. For Linux also rpm, deb, and pamac are available; I suggest using them!

Cheers

**Comment by SeinopSys** [comment]
Running into the same issue again.

**Comment by durgaswaroop** [comment]
I'm getting this again now.

**Comment by SeinopSys** [comment]
My solution was cloning the repo locally and building it for myself whenever this warning pops up, I'm no longer using the premade binaries.

If the maintainer wants to avoid this issue reappearing every so often, then putting an emphasis on how to build it and removing the premade binaries might be the simplest option.

**Comment by GitVIVIVI** [comment]
@steccas  As of today I am seeing this issue again. I am not sure how to build it for myself. 
I have been installing and updating via winget.
![image](https://user-images.githubusercontent.com/70075221/152027703-2e3f0bc6-13cb-4592-bd13-94655d579429.png)

**Comment by steccas** [comment]
Yes, I know, an update is going to be released by the end of this week. Unfortunately I can't keep up on time, I will setup some ci/cd to solve definitely.

**Comment by GitVIVIVI** [comment]
@steccas

I understand that it's hard to keep up and that you have other things to focus on. In any case, the application works perfectly for me. 

It's only that this warning dialog pops up every time I start it.

Irregardless of the warning dialog, do you reckon it's still safe to use the application?

**Comment by seascape** [comment]
Today I thought, well, time to resolve that startup error in ProtonClient. But ack, no updates yet. I hope all is OK.

**Comment by seascape** [comment]
Sounds like Proton.me is the new domain for all Proton services. There is an unclearable nag to move to Proton.me at the top of the client now. It is unclear if the protonmail.com domain that the client currently display will stick around indefinitely.
